const { SchemaType } = require("@google/generative-ai");

const diagnosisSchema = {
    type: SchemaType.OBJECT,
    description: "Output schema for medical diagnosis details",
    properties: {
        symptoms: {
            type: SchemaType.ARRAY,
            description: "List of symptoms experienced",
            items: {
                type: SchemaType.STRING,
            },
            nullable: false,
        },
        triggers: {
            type: SchemaType.ARRAY,
            description: "List of triggers that may exacerbate symptoms",
            items: {
                type: SchemaType.STRING,
            },
            nullable: false,
        },
        risk_level: {
            type: SchemaType.STRING,
            description: "Overall risk level (e.g. Low, Moderate, High)",
            nullable: false,
        },
        condition_category: {
            type: SchemaType.STRING,
            description: "Broad category/classification of the condition (e.g. 'Inflammatory Conditions')",
            nullable: false,
        },
        confidence: {
            type: SchemaType.NUMBER,
            description: "Confidence level for this diagnosis (0.0 - 1.0)",
            nullable: false,
        },
        recommendations: {
            type: SchemaType.ARRAY,
            description: "Recommended actions or lifestyle changes",
            items: {
                type: SchemaType.STRING,
            },
            nullable: false,
        },
        follow_up: {
            type: SchemaType.ARRAY,
            description: "Suggested follow-up actions or consultations",
            items: {
                type: SchemaType.STRING,
            },
            nullable: false,
        },
    },
    required: [
        "symptoms",
        "triggers",
        "risk_level",
        "condition_category",
        "confidence",
        "recommendations",
        "follow_up",
    ],
};

const QUESTIONS = [
    {
        id: 1,
        text: "I ______ experience bloating or gas.",
        displayText: "How often do you experience bloating or gas?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 2,
        text: "I ______ experience constipation or diarrhea.",
        displayText: "How often do you experience constipation or diarrhea?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 3,
        text: "I experience _______ symptoms regularly.",
        displayText: "Which symptoms do you experience regularly?",
        multiSelect: true,
        options: [
            "Acid reflux",
            "Nausea",
            "Diarrhea",
            "Bloating",
            "Fatigue after meals",
        ],
    },
    {
        id: 4,
        text: "I ______ experience discomfort or pain after eating.",
        displayText: "How often do you experience discomfort or pain after eating?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 5,
        text: "Eating spicy or fatty foods ______ worsens my symptoms.",
        displayText: "How do spicy or fatty foods affect your symptoms?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 6,
        text: "I avoid ______ due to intolerance or discomfort.",
        displayText: "Which foods do you avoid due to intolerance or discomfort?",
        multiSelect: true,
        options: ["Gluten", "Fried foods", "Dairy", "Spicy foods"],
    },
    {
        id: 7,
        text: "I ______ feel fatigue, especially after meals.",
        displayText: "How often do you feel fatigue, especially after meals?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 8,
        text: "I experience ______ inflammatory symptoms.",
        displayText: "Which inflammatory symptoms do you experience?",
        multiSelect: true,
        options: ["Abdominal pain", "Diarrhea", "Bloating"],
    },
    {
        id: 9,
        text: "I ______ experience flare-ups of gut symptoms (e.g., diarrhea, cramping).",
        displayText: "How often do you experience flare-ups of gut symptoms (e.g., diarrhea, cramping)?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 10,
        text: "I ______ experience changes in my gut symptoms when under stress.",
        displayText: "How often do you experience changes in your gut symptoms when under stress?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 11,
        text: "My symptoms ______ wake me up at night.",
        displayText: "How often do your symptoms wake you up at night?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 12,
        text: "I ______ experience worsened symptoms after consuming processed or fried foods.",
        displayText: "How often do you experience worsened symptoms after consuming processed or fried foods?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 13,
        text: "I experience ______ that may indicate gut microbiome imbalances.",
        displayText: "Which symptoms do you experience that may indicate gut microbiome imbalances?",
        multiSelect: true,
        options: [
            "Frequent bloating",
            "Sugar cravings",
            "Weight loss without diet changes",
        ],
    },
    {
        id: 14,
        text: "I ______ consume fermented foods like yogurt, kimchi, or sauerkraut.",
        displayText: "How often do you consume fermented foods like yogurt, kimchi, or sauerkraut?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 15,
        text: "I ______ take antibiotics.",
        displayText: "How often do you take antibiotics?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 16,
        text: "I ______ experience unexplained fatigue or low energy.",
        displayText: "How often do you experience unexplained fatigue or low energy?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 17,
        text: "I ______ experience sugar cravings.",
        displayText: "How often do you experience sugar cravings?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 18,
        text: "I ______ experience difficulty maintaining or losing weight despite a healthy lifestyle.",
        displayText: "How often do you experience difficulty maintaining or losing weight despite a healthy lifestyle?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 19,
        text: "I ______ notice changes in my digestion when I am anxious or stressed.",
        displayText: "How often do you notice changes in your digestion when you are anxious or stressed?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 20,
        text: "I ______ feel stressed in a typical week.",
        displayText: "How often do you feel stressed in a typical week?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 21,
        text: "I ______ experience changes (more or less) in eating patterns during periods of high stress.",
        displayText: "How often do you experience changes (more or less) in eating patterns during periods of high stress?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 22,
        text: "I ______ experience trouble falling or staying asleep.",
        displayText: "How often do you experience trouble falling or staying asleep?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 23,
        text: "I experience ______ during times of stress.",
        displayText: "Which symptoms do you experience during times of stress?",
        multiSelect: true,
        options: ["Nausea", "Abdominal pain", "Diarrhea"],
    },
    {
        id: 24,
        text: "I ______ engage in late-night eating or snacking.",
        displayText: "How often do you engage in late-night eating or snacking?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 25,
        text: "I experience ______ regularly.",
        displayText: "Which symptoms do you experience regularly?",
        multiSelect: true,
        options: [
            "Frequent muscle cramps",
            "Fatigue despite meals",
            "Frequent bloating",
        ],
    },
    {
        id: 26,
        text: "I ______ feel overly full or uncomfortable after eating.",
        displayText: "How often do you feel overly full or uncomfortable after eating?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 27,
        text: "I ______ experience fatigue despite eating balanced meals.",
        displayText: "How often do you experience fatigue despite eating balanced meals?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 28,
        text: "I ______ eat meals in a rush or while distracted.",
        displayText: "How often do you eat meals in a rush or while distracted?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
    {
        id: 29,
        text: "I experience _______ regularly.",
        displayText: "Which symptoms do you experience regularly?",
        multiSelect: true,
        options: [
            "Weight loss without diet changes",
            "Frequent muscle cramps",
            "Bloating",
        ],
    },
    {
        id: 30,
        text: "I ______ feel hungry soon after eating meals.",
        displayText: "How often do you feel hungry soon after eating meals?",
        multiSelect: false,
        options: ["Never", "Occasionally", "Frequently", "Always"],
    },
];

module.exports = {diagnosisSchema, QUESTIONS}